// <auto-generated />
using System;
using CompanyManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyManagement.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240517055046_addedProjectDetails")]
    partial class addedProjectDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyManagement.Data.EmployeeDetails", b =>
                {
                    b.Property<int>("empId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empId"));

                    b.Property<string>("empBloodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("empDob")
                        .HasColumnType("datetime2");

                    b.Property<string>("empName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("empId");

                    b.ToTable("EmployeeDetails");
                });

            modelBuilder.Entity("CompanyManagement.Data.EmployeeProjectMap", b =>
                {
                    b.Property<int>("epId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("epId"));

                    b.Property<int>("empId")
                        .HasColumnType("int");

                    b.Property<int>("projectId")
                        .HasColumnType("int");

                    b.HasKey("epId");

                    b.ToTable("employeeProjectMaps");
                });

            modelBuilder.Entity("CompanyManagement.Data.EmployeeRoleMap", b =>
                {
                    b.Property<int>("erId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("erId"));

                    b.Property<int>("empId")
                        .HasColumnType("int");

                    b.Property<string>("roleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("erId");

                    b.ToTable("employeeRoleMaps");
                });

            modelBuilder.Entity("CompanyManagement.Data.LeaveDetails", b =>
                {
                    b.Property<int>("leaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("leaveId"));

                    b.Property<int>("empId")
                        .HasColumnType("int");

                    b.Property<int>("leaveLOP")
                        .HasColumnType("int");

                    b.Property<int>("leavePaidRemain")
                        .HasColumnType("int");

                    b.Property<int>("leavePaidTaken")
                        .HasColumnType("int");

                    b.HasKey("leaveId");

                    b.ToTable("LeaveDetails");
                });

            modelBuilder.Entity("CompanyManagement.Data.ProjectDetails", b =>
                {
                    b.Property<int>("projectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("projectId"));

                    b.Property<DateTime>("projectDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("projectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("projectNumResource")
                        .HasColumnType("int");

                    b.Property<DateTime>("projectStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("projectId");

                    b.ToTable("ProjectDetails");
                });

            modelBuilder.Entity("CompanyManagement.Models.EmployeeDetailsModel", b =>
                {
                    b.Property<int>("empId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empId"));

                    b.Property<string>("empBloodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empCity")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("empContact")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("empCountry")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("empDob")
                        .HasColumnType("datetime2");

                    b.Property<string>("empName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("empState")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("empId");

                    b.ToTable("EmployeeDetailsModel");
                });
#pragma warning restore 612, 618
        }
    }
}
